FROM python:3.9.0-alpine

ENV APP_USER snyk_watcher
ENV APP_DIR /home/$APP_USER
WORKDIR $APP_DIR

# Create user and group
RUN addgroup -S $APP_USER &&\
    adduser	 -S -G $APP_USER -s /sbin/nologin $APP_USER

RUN apk update

COPY requirements.txt $APP_DIR/requirements.txt
COPY tests/requirements_test.txt $APP_DIR/requirements_test.txt

RUN apk add --virtual build-dependencies python3-dev build-base \
	&& pip3 install --upgrade pip \
	&& pip3 install -r $APP_DIR/requirements.txt \
	&& pip3 install -r $APP_DIR/requirements_test.txt \
	&& rm -rf /var/cache/apk/* \
	&& apk del build-dependencies

COPY app $APP_DIR/app
COPY tests $APP_DIR/tests

USER $APP_USER

CMD (python -m pytest -v -s && pycodestyle -v app)
